# Generated by Django 4.0.3 on 2022-04-26 22:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogs_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
